services:
  db:
    image: mongo:7.0
    restart: always

    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: wiseai
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

    networks:
      - wiseai

networks:
  wiseai:
